### ISSUE TITLE
GetChatHistoryAsync() only returns last message and with "MessageContent.MessageUnsupported"

### ISSUE THREAD

**Issue by KomodoCrypto** [egramtel/tdsharp#103]
I am trying to get the last messages using GetChatHistoryAsync as:

`var result= TdApi.GetChatHistoryAsync(_client, chatTestId, limit: 10).Result;`

However, I am only getting one result with "{TdLib.TdApi.MessageContent.MessageUnsupported}".

1. About the amount of results, I tested with more chats and always returns 1 item. Why if I have limit 10? Do I forget something?
2. I am processing some text messages and photos properly with proper. Content property. However, for some messages, apparently with normal text and photo, I am getting Unsupported. How can I get more info? Can it be encrypted or some other option available for the admin of the group?

thanks

**Comment by x2bool** [comment]
I can propose to enable logging to see what messages cause the MessageUnsupported events

**Comment by KomodoCrypto** [comment]
Ok, based on the tdlib issues from tdlib comments, it seems that the version must be upgraded to 1.8.1.
I am trying to build it but I am dealing wihth some problems. Can we have it compiled?

**Comment by x2bool** [comment]
https://github.com/egramtel/tdsharp/issues/104
