### ISSUE TITLE
1.8.x bindings

### ISSUE THREAD

**Issue by x2bool** [egramtel/tdsharp#104]

**Comment by ForNeVeR** [comment]
FYI, tdlib.native 1.8.1 is ready (taken from commit [`1e1ab5d1b0e4811e6d9e1584a82da08448d0cada`](https://github.com/tdlib/td/commit/1e1ab5d1b0e4811e6d9e1584a82da08448d0cada), thanks for @YogurtTheHorse.

I am not publishing it to NuGet, yet, to avoid users' confusion. Let's do a coordinated update of both tdlib.native and tdsharp.

**Comment by KomodoCrypto** [comment]
Oh great, thanks! I understand that is better to wait until the NuGet package will be uploaded? I am trying to build it for .Net Core but I am still dealing with some issues...

**Comment by x2bool** [comment]
Guys, I am kind of far away from home. I don't know when I am going to have opportunity to generate bindings. So if someone will generate them, I will merge.

**Comment by ForNeVeR** [comment]
@x2bool, this is absolutely okay, no pressure is present and has never been. We are working on the bindings.

**Comment by KomodoCrypto** [comment]
Thanks for the update to 1.8.1 nd the efforts!
I already upgrade from 1.7.9 to 1.8.1. However, it doesn't solve my specific the problem. I am still getting TdLib.TdApi.MessageContent.MessageUnsupported for all messages in a chat.
What could be the reason? It is possible that the sender encrypts the message? Is there any other method to receive the raw data?

**Comment by ForNeVeR** [comment]
@KomodoCrypto, it is unclear how have you updated from what to what exactly.

**Comment by KomodoCrypto** [comment]
@ForNeVeR, sorry my mistake, I took the 'Merge pull request #100 from 0x25CBFC4F/sample-rework' commit. I wait then for the [Update ](https://github.com/egramtel/tdsharp/pull/105)
Many thanks
