### ISSUE TITLE
After months of running I get this error suddenly "Unable to load shared library 'tdjson'"

### ISSUE THREAD

**Issue by ikkeflikkeri** [egramtel/tdsharp#108]
So I created an app which has been working for a couple months on linux using tdsharp.
But since 2 week ago it suddenly stopped working and gave this error:

Unhandled exception. System.DllNotFoundException: Unable to load shared library 'tdjson' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libtdjson: cannot open shared object file: No such file or directory

This happened on all of my 5 servers, even different providers, no code or files changed but suddenly couldn't find tdjson anymore.
I tried to get this fixed but I wasn't able to get this fixed, I have no clue how this happened suddenly or how to fix this.

Does anybody have an idea on why this happened? I know there are a few other issues about this but it worked before and now it doesn't.

Project file:
![image](https://user-images.githubusercontent.com/2629360/160906682-baea84e4-c643-41e9-bc11-8566b1d3bdd2.png)

Dotnet Info:
![image](https://user-images.githubusercontent.com/2629360/160906617-5360c8bd-d94c-464b-a10d-57c87450691d.png)

**Comment by ForNeVeR** [comment]
Okay, and is there `libtdjson.so` file somewhere in the path you're deploying your application? Have you tried defining `LD_DEBUG` environment variable?

**Comment by ikkeflikkeri** [comment]
Yes, the library file is there, in the LD_DEBUG log it also says it can bind the file.
The complete log is here: [debug log.txt](https://github.com/egramtel/tdsharp/files/8391237/debug.log.txt)
I have no clue what wrong here.

**Comment by ForNeVeR** [comment]
@ikkeflikkeri, is it possible you have no `libssl.so.1.1`?

**Comment by ikkeflikkeri** [comment]
I did a file search and can't find libssl.so.1.1
"find: ‘libssl.so.1.1’: No such file or directory"
But openssl is installed on the server

**Comment by ikkeflikkeri** [comment]
Okay, upgrading to libssl 1.1.1 fixed this issue.
No idea how this suddenly happened on all my servers without changing any files.
Thanks for the help! :)
