### ISSUE TITLE
TDLib.Bindings vs TdLib.Bindings

### ISSUE THREAD

**Issue by ForNeVeR** [egramtel/tdsharp#114]
For now, we have two distinct namespaces: `TDLib.Bindings` and `TdLib.Bindings` for some reason.

We should figure it out and try to switch to some single one from these two.

**Comment by x2bool** [comment]
Yeah, that is probably just a typo I made somewhere.

**Comment by ForNeVeR** [comment]
Not only you, I have made it, too :)

The problem was that the case is different between the project files and the actual namespaces. I'm making a PR to make it all consistent (and hopefully don't break too many user code).

**Comment by ForNeVeR** [comment]
Okay, here's the strategy. There are three types which were in the wrong namespace: `TDLib.Bindings.ITdLibBindings`, `TDLib.Bindings.TdLibBindingsExtensions`, `TDLib.Bindings.TdLogLevel`.

The next non-bugfix tdsharp update (I assume, 1.9) will include them within a special compatibility layer (see `TdLib/LecagyCompat.cs`), and they will be marked as `[Obsolete]`.

The update after that (probably 1.10) will mark them as `[Obsolete(error: true)]`.

And the update after that (1.11?) will remove them.
