### ISSUE TITLE
Include documentation comments from td_api.tl in generated API bindings

### ISSUE THREAD

**Issue by silverdragon727** [egramtel/tdsharp#13]
Currently [td_api.tl](https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl) comes with documentation comments for all available TDLib methods and classes. 
Could you please include that as XML documentation comments in source files for generated API bindings?

**Comment by x2bool** [comment]
Fixed via https://github.com/egramtel/tdsharp/pull/17
