### ISSUE TITLE
AddProxy has no effect at all!

### ISSUE THREAD

**Issue by Salardx** [egramtel/tdsharp#14]
Could someone please give me an example of how we properly can use proxy (both Socks5 and Mtproto) here? coz when I use AddProxy nothing get returned, same applies to GetProxies.
If I could see an operational example, I'd highly appreciate it.

**Comment by x2bool** [comment]
Hi! AddProxy is used in egram. You can check out this file: https://github.com/egramtel/egram.tel/blob/master/src/Tel.Egram.Services/Settings/ProxyManager.cs

**Comment by Salardx** [comment]
Hi, The way I used your tool is a bit different, first I create the Client:
`
            private static Client _client = null;
            internal async static void TelegramClientInitiate()
            {
                if (_client != null) { _client.Dispose(); _client = null; }
                //--------/
                _client = new Client(); 
                //--------/
                ClientExecute(new TdApi.GetTextEntities() { Text = "@telegram /test_command https://telegram.org telegram.me @gif @test" });
                //--------/
                await utTask.RunForever(() => 
                {
                    while (!_quiting)
                    {
                        try
                        {
                            if (_client == null) break;
                            //--------/
                            string dataAsJson = _client.Receive(60000); if (string.IsNullOrEmpty(dataAsJson)) continue;
                            //--------/
                            OnClientReceived(dataAsJson);
                        }
                        catch (Exception ex) { Log(ex); }
                        finally { Thread.Sleep(10); }
                    }
                });
            }
`

Then I have some static methods, like these:

`
        private static string ClientExecute(TdApi.Object obj)
        {
            try
            {
                return _client.Execute(SerializeObject(obj));
            }
            catch (Exception ex) { Log(ex); return null; }
        }
        private static void ClientSend(TdApi.Object obj)
        {
            try
            {
                _client.Send(SerializeObject(obj));
            }
            catch (Exception ex) { Log(ex); }
        }
`

The problem is, when I call 
`string res = ClientExecute(new TdApi.GetProxies());`
res would become null and nothing happens, Also when I use ClientSend (Async mode) nothing gets returned...
Where I'm going wrong...

**Comment by x2bool** [comment]
You could try Client.SetVerbosityLevel(10) and see what goes wrong in the log

**Comment by Salardx** [comment]
Thanks, I did that, the result is:


[ 1][t 0][1548179687.219829321][ClientJson.cpp:90]	Failed to parse [request:{\0042@type\0042:\0042addProxy\0042,\0042@extra\0042:null,\0042server\0042:\0042shuydgyo.xyz\0042,\0042port\0042:443,\0042enable\0042:true,\0042type\0042:{\0042@type\0042:\0042proxyTypeMtproto\0042,\0042@extra\0042:null,\0042secret\0042:\0042dd8d6ab375709ab8f2a18d5602df229602\0042}}] [Error : 0 : Unknown class]
[ 3][t 4][1548179690.054081440][ConfigManager.cpp:448][!Recoverer][&config_recoverer]	Failed to connect for 20.011393
[ 3][t 4][1548179690.054172754][ConfigManager.cpp:476][!Recoverer][&config_recoverer]	ASK SIMPLE CONFIG
[ 3][t 4][1548179690.054225683][ConfigManager.cpp:109][!Recoverer][&config_recoverer]	Request simple config from https://software-download.microsoft.com/prod/config.txt
[ 3][t 4][1548179690.054272652][ConfigManager.cpp:510][!Recoverer][&config_recoverer]	Wakeup NEVER
[ 3][t 2][1548179690.055701017][IPAddress.cpp:151][!Wget]	Try to init IP address of software-download.microsoft.com with port 443
[ 3][t 2][1548179690.197585583][IPAddress.cpp:189][!Wget]	Have ipv4 address 0.0.0.0 with port 0
[ 3][t 4][1548179690.198312998][ConfigManager.cpp:368][!Recoverer][&config_recoverer]	Get SimpleConfig error [Error : 0 : TODO]
[ 3][t 4][1548179690.198384523][ConfigManager.cpp:448][!Recoverer][&config_recoverer]	Failed to connect for 20.155622
[ 3][t 4][1548179690.198441267][ConfigManager.cpp:507][!Recoverer][&config_recoverer]	Wakeup in 19.0s
[ 3][t 4][1548179691.046589613][AuthData.cpp:57][!Session:4:main]	no salt
[ 2][t 4][1548179691.046771526][Session.cpp:384][!Session:4:main]	on_closed: [WindowsError : The semaphore timeout period has expired. : 121 : ConnectEx failed] Session:4:main::Connect::Tcp::[149.154.167.91:443] DcId{4}[0.0.0.0:54058]
[ 4][t 4][1548179691.047638893][DcOptionsSet.cpp:60][!ConnectionCreator]	Skip media only option
[ 4][t 4][1548179691.047677994][DcOptionsSet.cpp:60][!ConnectionCreator]	Skip media only option
[ 3][t 4][1548179691.047720909][ConnectionCreator.cpp:395][!ConnectionCreator]	Create: [[2001:67c:4e8:f004::a]:443] DcId{4}
[ 2][t 4][1548179691.047968149][ConnectionCreator.cpp:400][!ConnectionCreator]	[WindowsError : The requested address is not valid in its context. : 10049 : Failed to bind a socket]
[ 3][t 4][1548179691.048267841][Session.cpp:1182][!Session:4:main]	Wakeup After 1000.000000
[ 3][t 4][1548179691.148501873][ConnectionCreator.cpp:538][!ConnectionCreator]	[hash:0x64f987e3] wakeup
[ 3][t 4][1548179691.578213215][ConnectionCreator.cpp:538][!ConnectionCreator]	[hash:0x64f987e3] wakeup
[ 4][t 4][1548179691.578314781][DcOptionsSet.cpp:60][!ConnectionCreator]	Skip media only option
[ 4][t 4][1548179691.578343153][DcOptionsSet.cpp:60][!ConnectionCreator]	Skip media only option
[ 3][t 4][1548179691.578379869][ConnectionCreator.cpp:395][!ConnectionCreator]	Create: [149.154.167.91:80] DcId{4}
[ 3][t 4][1548179691.579177856][RawConnection.cpp:53][!PingActor]	Send handshake packet: 
00000000 00000000 00000001 00000000 00000014 be7e8ef1 07542129 de9e7093 8787e1e8 271d86be



You have any idea?
This is the way I call AddProxy:
`                        stRes = ClientExecute(new TdApi.AddProxy() { Server = DEF_M_PROXY_SERVER, Port = DEF_M_PROXY_PORT, Enable = true, Type = new ProxyType.ProxyTypeMtproto() { Secret = DEF_M_PROXY_SECRET } });
`

**Comment by x2bool** [comment]
Well it says it failed to parse request.

Try using Dialer class as suggested in README. It handles asynchronicity behind the scenes. And you don't have to serialize/deserialize requests manually.

My guess is that SerializeObject(obj) produces property names with incompatible format.

```
TdApi.Ok ok = await dialer.ExecuteAsync(new TdApi.AddProxy
{
    Server = proxy.Server,
    Port = proxy.Port,
    Type = proxy.Type
});
```

Try this. This code would either return ok or throw. BTW Execute method is meant to be used only for some of the methods by TDLib authors.

**Comment by Salardx** [comment]
Thank you for your comment, I changed the code the way you said, still no result...

        private static Client _client = null;
        private static Dialer _dl = null;

            internal async static void TelegramClientInitiate()
            {
                if (_client != null) { _client.Dispose(); _client = null; }
                //--------/
                _client = new Client(); _quiting = false; _haveAuthorization = false; 
                _client.SetVerbosityLevel(10);
                _dl = new Dialer(_client, new Hub(_client));
                //--------/
                await utTask.RunForever(() => 
                {
                    while (!_quiting)
                    {
                        try
                        {
                            if (_client == null) break;
                            //--------/
                            string dataAsJson = _client.Receive(60000); if (string.IsNullOrEmpty(dataAsJson)) continue;
                            //--------/
                            OnClientReceived(dataAsJson);
                        }
                        catch (Exception ex) { Log(ex); }
                        finally { Thread.Sleep(10); }
                    }
                });
            }

             internal static void ProxyApply()
             {
                        TdApi.Object obj = ClientExecute(new TdApi.AddProxy() { Server = DEF_M_PROXY_SERVER, Port = DEF_M_PROXY_PORT, Enable = true, Type = new ProxyType.ProxyTypeMtproto() { Secret = DEF_M_PROXY_SECRET } });
            }

**Comment by x2bool** [comment]
You have to start hub as noted in README:
```csharp
_client = new Client();
_hub = new Hub();
_dialer = new Dialer(_client, _hub);

_hub.Start();

TdApi.Ok ok = await _dialer.ExecuteAsync(new TdApi.AddProxy
{
    Server = proxy.Server,
    Port = proxy.Port,
    Type = proxy.Type
});
```

**Comment by Salardx** [comment]
What would you say if I tell you that I did exactly what you suggested but the same error keeps showing up
`[ 1][t 0][1548439196.043021441][ClientJson.cpp:90]	Failed to parse [request:{\0042@type\0042:\0042addProxy\0042,\0042@extra\0042:\0042\0042,\0042server\0042:\0042shuydgyo.xyz\0042,\0042port\0042:443,\0042enable\0042:true,\0042type\0042:{\0042@type\0042:\0042proxyTypeMtproto\0042,\0042@extra\0042:\0042\0042,\0042secret\0042:\0042dd8d6ab375709ab8f2a18d5602df229602\0042}}] [Error : 0 : Unknown class]
`

**Comment by Salardx** [comment]
Will you please show me the Log of yours when you set addProxy? I mean I want to at least see what kinda structure you serialized that tdjson.dll accepted. because clearly it says that my structure of addProxy is invalid...
this is my structure:
    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class TdApi
    {
        public class AddProxy : Function<Proxy>
        {
            [JsonProperty("@type")] public override string DataType { get; set; } = "addProxy";

            [JsonProperty("@extra")] public override string Extra { get; set; } = "";

            [JsonConverter(typeof(Converter))]
            [JsonProperty("server")]
            public string Server { get; set; }

            [JsonConverter(typeof(Converter))]
            [JsonProperty("port")]
            public int Port { get; set; }

            [JsonConverter(typeof(Converter))]
            [JsonProperty("enable")]
            public bool Enable { get; set; }

            [JsonConverter(typeof(Converter))]
            [JsonProperty("type")]
            public ProxyType Type { get; set; }
        }
    }

**Comment by x2bool** [comment]
Hi, sorry it took so long for me to respond. Here are the logs (I removed server and secret from there):

```
[ 3][t 4][1548966451.256130219][Td.cpp:3308][!Td][&td_requests]	Receive request 5: addProxy {
  server = ""
  port = 2000
  enable = false
  type = proxyTypeMtproto {
    secret = ""
  }
}

[ 3][t 4][1548966451.263210058][Td.cpp:4253][!Td][&td_requests]	Sending result for request 5: proxy {
  id = 2
  server = ""
  port = 2000
  last_used_date = 0
  is_enabled = false
  type = proxyTypeMtproto {
    secret = ""
  }
}

[ 3][t 4][1548966474.343198061][Td.cpp:3308][!Td][&td_requests] Receive request 6: enableProxy {
  proxy_id = 2
}
```
