### ISSUE TITLE
How to get user_id by phone number without ImportContacts

### ISSUE THREAD

**Issue by Salardx** [egramtel/tdsharp#15]
Other than ImportContacts, Is there anyway to know the user_id by phone number?
Or at least a way to realize that a phone number is registered in telegram or not...

**Comment by x2bool** [comment]
As far as I know - no. This type of questions is better to be asked here: https://github.com/tdlib/td/issues

**Comment by x2bool** [comment]
Closed: https://github.com/tdlib/td/issues/483
