### ISSUE TITLE
Update issue with version 1.8.9

### ISSUE THREAD

**Issue by atiyka** [egramtel/tdsharp#152]
I updated to the latest version, but I could not even initialize the library. 
It throws an exception, when setting the tdlib parameters (I do the same way as you did in the `new` sample)
```
await _client.ExecuteAsync(new TdApi.SetTdlibParameters
    {
        ApiId = ApiId,
        ApiHash = ApiHash,
        DeviceModel = "PC",
        SystemLanguageCode = "en",
        ApplicationVersion = ApplicationVersion,
        DatabaseDirectory = filesLocation,
        FilesDirectory = filesLocation
    });
```
The exception is the following:
![image](https://user-images.githubusercontent.com/9460253/207035900-c237ee77-9df2-440d-b81a-f03cf1bba5ca.png)

I tried also to set every possible parameter, but I still got the same exception.
Do you have any idea?

**Comment by ForNeVeR** [comment]
What tdlib build and version do you use? I mean, not tdsharp, but tdlib itself.

**Comment by atiyka** [comment]
Good point! I don't know how can I check that, but I rebuilt the tdlib and now everything works fine, thank you! :)
