### ISSUE TITLE
Activate or generate a Notification when a message is received to 'Saved Messages' chat

### ISSUE THREAD

**Issue by KomodoCrypto** [egramtel/tdsharp#158]
I am sending messages to the chat_Id that corresponds to the same client. So that messages are received properly into 'Saved Messages' chat. 
However, this chat doesn't allow to activate notifications. I assume that, from the user client app point of view, it doesn't make sense to receive a message sent by yourself. However, it does make sense for an own client development, where I am using it to filter and group other information.
Then, how to create a notification when a message is received in the self chat_Id ('Saved Messages')?
Code that I am using to send the messages:

          ```
  ```
var content = new TdApi.InputMessageContent.InputMessageText
            {
                Text = new TdApi.FormattedText { Text = "testing", Entities = null },
                ClearDraft = false,
                DisableWebPagePreview = true
            };
```

            var sendMessage = await _client.ExecuteAsync(new TdApi.SendMessage
            {
                ChatId = longMySelfChatId,
                InputMessageContent = content
            });
```

```
Update:
I am trying also to send a notification to another chatId (not the self chatId, and with the notifications activated), but I am not receiving the notification.
```

            var _Options = new TdApi.MessageSendOptions { DisableNotification = false };

            var sendMessage = await _client.ExecuteAsync(new TdApi.SendMessage
            {
                ChatId = _chatId,
                InputMessageContent = content,
                Options = _Options,
            });

**Comment by ForNeVeR** [comment]
Sadly, I believe that's a question for [TDLib](https://github.com/tdlib/td), and not for us.
