### ISSUE TITLE
call TdApi.CheckChatInviteLink Async

### ISSUE THREAD

**Issue by Behnam-Emamian** [egramtel/tdsharp#16]
Hi

I can call asynchronous most of the api but it is not working for "TdApi.CheckChatInviteLink". Do you know why?

**Comment by x2bool** [comment]
Hi,

It's hard to tell without logs. Try `Client.Log.SetVerbosityLevel(10)`.

**Comment by Behnam-Emamian** [comment]
I have enabled the log and I can see the huge amount of log, how can I filter it just for this command?

this is the code:
var linkInfo = await SendCheckChatInviteLinkAsync(inviteLink);

async Task<ChatInviteLinkInfo> SendCheckChatInviteLinkAsync(string inviteLink)
        {
            return await _apiService.dialer.ExecuteAsync(new TdApi.CheckChatInviteLink
            {
                InviteLink = inviteLink
            }
            );
        }

**Comment by x2bool** [comment]
I would try `Client.Log.SetFilePath()` to write logs to a file. Then you could search for `checkChatInviteLink`.

**Comment by x2bool** [comment]
Closing for now. Feel free to report more details.
