### ISSUE TITLE
Support of spoilers

### ISSUE THREAD

**Issue by nredko** [egramtel/tdsharp#161]
Current version from NuGet doesn't recognize spoiled images and returns MessageContentUnsupported.
Could you update with latest TDLib?

**Comment by ForNeVeR** [comment]
For the record, I wasn't able to find anything related to spoilers in the update. Yet it's almost always a good idea to update TDLib, so I'll do what's possible.

**Comment by ForNeVeR** [comment]
v1.8.12 is out but unlisted on nuget.org for now. I'm working on getting a corresponding release for tdlib.native right now.

**Comment by ForNeVeR** [comment]
Finally, v1.8.12 is available for installation and listed. Please check if it works for you.
