### ISSUE TITLE
`updateChatMessageTtl` is not implemented and resulted in exception thrown

### ISSUE THREAD

**Issue by DamienLaw** [egramtel/tdsharp#167]
[`updateChatMessageTtl`](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1update_chat_message_ttl.html#a5f0e8676b28ac97c761abc0776da1236) is not implemented and when received from Telegram will result in an exception thrown.

> Could not create an instance of type TdLib.TdApi+Object. Type is an interface or abstract class and cannot be instantiated. Path '@type', line 1, position 9.

https://github.com/egramtel/tdsharp/blob/9bebcfafe4a0ea8a998782af1b928276b608febe/TdLib/Bindings/Receiver.cs#L43-L69
This is because on line `54`, the deserialization will fallback to `TdApi.Object` if the type is not found.

https://github.com/egramtel/tdsharp/blob/9bebcfafe4a0ea8a998782af1b928276b608febe/TdLib.Api/Object.cs#L10-L15
And `TdApi.Object` is **abstract**. No deserialization can be performed on abstract class.

**Comment by ForNeVeR** [comment]
Any idea what exactly is this message? I cannot find it in `td_api.tl` from tdlib: https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl

**Comment by ForNeVeR** [comment]
In fact, it is **only** mentioned in an old changelog (from 1.8.0, 2021-12-29), and nowhere else.

Are you sure it exists? Under what circumstances do you receive that?

**Comment by DamienLaw** [comment]
When I was running the C# sample `TdLib.Samples.GetChats`. 

I'm only getting error on one of my accounts. But not on the other.

**Comment by ForNeVeR** [comment]
Why do you think that's `updateChatMessageTtl` and not something else? Have you found that in debug mode?

**Comment by DamienLaw** [comment]
Yes, I was running the sample in debug mode when I was hit by the exception. 

![image](https://user-images.githubusercontent.com/14930009/232328504-b30528bc-6af2-4779-8bcc-2a3d6b960795.png)

The `@type` indicated that it's `updateChatMessageTtl` (underlined at the lower left of the screenshot).

**Comment by ForNeVeR** [comment]
I would recommend opening an issue upstream.

There is no such type in the actual tdlib sources, and I don't understand how we should generate it.

**Comment by DamienLaw** [comment]
The reference is specified [here](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1update_chat_message_ttl.html) and [here](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1update_chat_message_ttl.html).

Does it help?

**Comment by ForNeVeR** [comment]
These links look identical. And, unfortunately, no, it does not help.

There are still no any details about this class in the `.tl` specification. So, we cannot generate it. And it doesn't exist in tdlib sources.

**Comment by DamienLaw** [comment]
> These links look identical.

Sorry, the 2nd link supposed to be [td_api.h](https://core.telegram.org/tdlib/docs/td__api_8h_source.html)

Perhaps, that class has been removed from the API but the server is still sending it. Is it possible to ignore unrecognised API and logs them instead of throwing unhandled exceptions and killing the client?

**Comment by ForNeVeR** [comment]
> Perhaps, that class has been removed from the API but the server is still sending it.

On this, I unfortunately have no idea. This is a question for upstream developers.

> Is it possible to ignore unrecognised API and logs them instead of throwing unhandled exceptions and killing the client?

But we are doing that already. An `ExceptionThrown` event is emitted when there's an exception in the `Receiver` loop; there are no unhandled exceptions anywhere.

(Also, I found that the exception is not even exposed anywhere, I'll create an improvement request for that matter.)

Do you suggest some other behavior?

**Comment by DamienLaw** [comment]
You're right, there's no unhandled exception. I was only receiving that during debugging. It's not really an issue then. I'll proceed to close this issue. Thanks for your time looking into this.
