### ISSUE TITLE
Incorrect shared object name in macOS binding 

### ISSUE THREAD

**Issue by njlr** [egramtel/tdsharp#172]
The macOS bindings expect a `dylib` file called `liblibtdjson.dylib` on the search path. However, the standard build for [TDLib](https://github.com/tdlib/td) will output a file called `libtdjson.dylib`.

I believe that the problem line is here: https://github.com/egramtel/tdsharp/blob/c74c96e5aadb957453855c2978f487a82fa43182/TdLib/Bindings/MacosBindings.cs#L8

The `lib` prefix is added automatically, so it should be:

```csharp
private const string Dll = "tdjson.dylib";
```

Thanks :+1:

**Comment by njlr** [comment]
Ah nope, it works

**Comment by ForNeVeR** [comment]
Glad to hear it works for you!
