### ISSUE TITLE
How to use SetOption?

### ISSUE THREAD

**Issue by AqlaSolutions** [egramtel/tdsharp#174]
This never return:

```
await _client.SetOptionAsync("localization_target", new TdApi.OptionValue { DataType = "optionValueString", Extra = "android" });
await _client.SetOptionAsync("language_pack_id", new TdApi.OptionValue { DataType = "optionValueString", Extra = "en" });
```

**Comment by ForNeVeR** [comment]
Could you please check the threading? In most cases, calls that never return are caused by awaiting them on the (already blocked) UI thread.

**Comment by AqlaSolutions** [comment]
May be I was not clear but the questions is not really about it not returning but about that there is no possibility to use `OptionValue` to set anything because in the native TdLib you use StringOptionValue, IntOptionValue, etc but here you have only plain `OptionValue`. I tried to use it anyway but it didn't work out.

**Comment by AqlaSolutions** [comment]
btw there is no UI thead because I'm experimenting with console app

**Comment by ForNeVeR** [comment]
Try this:
```
await _client.SetOptionAsync("foo", new TdApi.OptionValue.OptionValueString { Value = "test" });
```

Would that work?

**Comment by AqlaSolutions** [comment]
Ah, I couldn't find it. Thanks.

Also the reason it was not returning was that it doesn't work until SetTdlibParameters is called.
