### ISSUE TITLE
Android Support for .NET MAUI

### ISSUE THREAD

**Issue by nikolaykusch** [egramtel/tdsharp#176]
I am using this library for .NET MAUI Desktop, and everything works great.
But is there a way to run it on mobile platforms, particularly Android?

**Comment by ForNeVeR** [comment]
Of course. You'll just need to build tdlib on your own, and then tdsharp is able to use it. Take a look at the [**Overriding native bindings**](https://github.com/egramtel/tdsharp#overriding-native-bindings) entry of the documentation.

On how to build tdlib for Android I can't help, but they seem to have build instructions in [tdlib documentation](https://github.com/tdlib/td).

**Comment by nikolaykusch** [comment]
But there is no mention of Android in Bindings

**Comment by ForNeVeR** [comment]
<img width="667" alt="image" src="https://github.com/egramtel/tdsharp/assets/92793/65eb4018-6762-4308-967a-31ad2b4817b7">

**Comment by nikolaykusch** [comment]
Ok, thanks, will try
