### ISSUE TITLE
AddProxyAsync never returns

### ISSUE THREAD

**Issue by wizche** [egramtel/tdsharp#186]
I'm experiencing the same problem described in #84.
Using the latest versions: `libtdjson.so.1.8.23` and `TDLib 1.8.21` (but also tried different versions too) 
In the following code

```
var client = new TdClient();
Console.WriteLine(
    $"Configuring proxy {username}:{new string('*', pwd.Length)}@{host}:{port}");
var httpProxy = new TdApi.ProxyType.ProxyTypeHttp()
{
    Username = username,
    Password = pwd,
    HttpOnly = true,
};
var proxy = await client.AddProxyAsync(host, port, true, httpProxy);
Console.WriteLine($"Proxy {proxy.Id} enabled");
```
The async call `AddProxyAsync` never returns. 
 
Using .NET 8.0 on Debian 11 (bullseye)

**Comment by ForNeVeR** [comment]
Does it reproduce in a new console app? Could you try debugging that?

**Comment by ForNeVeR** [comment]
I also note that the versions do not correspond each other. Could you try libtdjson 1.8.21?

**Comment by ForNeVeR** [comment]
Nope, I can't confirm it works now. To clarify, the full example is
```csharp
var _client = new TdClient();
var host = "localhost";
var port = 8080;
var username = "";
var pwd = "";
Task.Run(async () => {
    Console.WriteLine($"Configuring proxy {username}:{new string('*', pwd.Length)}@{host}:{port}");
    var httpProxy = new TdApi.ProxyType.ProxyTypeHttp()
    {
        Username = username,
        Password = pwd,
        HttpOnly = false,
    };

    var proxy = await _client.AddProxyAsync(host, port, true, httpProxy);
    Console.WriteLine($"Proxy {proxy.Id} enabled");
});
```

Your code is now different, `_client` instead of `client`. Are you doing it in a UI app? This would mean a lot of difference in how async tasks are processed.

**Comment by wizche** [comment]
I left it out because I feared that with `await` keyword the task will be scheduled in the main thread instead of a running on a separate one. And indeed, if I use `await` it does not work. Did you try without `await`?

You see the `_client` because I moved from the simple repro example to the sample `TdLib.Samples.GetChats` to actually see if the proxy was used/working. But again they were both console apps.

I'm pretty sure thats the main issue, if the main-thread is used it gets stuck, thats why this works:
```
await Task.Factory.StartNew(async () => {
                                 Console.WriteLine(
                                                    $"Configuring proxy {username}:{new string('*', pwd.Length)}@{host}:{port}");
                                                var httpProxy = new TdApi.ProxyType.ProxyTypeHttp()
                                                {
                                                    Username = username,
                                                    Password = pwd,
                                                    HttpOnly = false,
                                                };
                                                
                                                var proxy = await _client.AddProxyAsync(host, port, true, httpProxy);
                                                Console.WriteLine($"Proxy {proxy.Id} enabled");
                                }, TaskCreationOptions.LongRunning);
```
With the `LongRunning` flag it _should_ force the task on a different thread so that even if I `await` it, it works.

**Comment by ForNeVeR** [comment]
> I left it out because I feared that with `await` keyword the task will be scheduled in the main thread instead of running on a separated one. And indeed, if I use `await` it does **not** work. Did you try without `await`?

But the end program won't wait for the task completion, then. What's the point?

> ```
> await Task.Factory.StartNew(async () => {
>                                  Console.WriteLine(
>                                                     $"Configuring proxy {username}:{new string('*', pwd.Length)}@{host}:{port}");
>                                                 var httpProxy = new TdApi.ProxyType.ProxyTypeHttp()
>                                                 {
>                                                     Username = username,
>                                                     Password = pwd,
>                                                     HttpOnly = false,
>                                                 };
>                                                 
>                                                 var proxy = await _client.AddProxyAsync(host, port, true, httpProxy);
>                                                 Console.WriteLine($"Proxy {proxy.Id} enabled");
>                                 }, TaskCreationOptions.LongRunning);
> ```

This program still misbehaves and doesn't wait for the `AddProxyAsync` to return. If you inspect the type returned by `Task.Factory.StartNew`, you'll see it's `Task<Task>`. So, you'd need to write `await await Task.Factory.StartNew`.

I still insist on asking the upstream maintainers. The request of `AddProxyAsync` never receives a response, and that's the problem, not something else.

**Comment by wizche** [comment]
With the given code, at my side, it **does** return since I see the `Proxy 1 enabled` output. I will cross post this issue on their GitHub. 
Thanks for the help
