### ISSUE TITLE
TdLib.TdException: 'Chat not found'

### ISSUE THREAD

**Issue by StruninIhor** [egramtel/tdsharp#189]
Using the code provided in https://github.com/egramtel/tdsharp/tree/master/Samples/TdLib.Samples.GetChats
I has modified the code to call getChatHistory.
The issue is happening sporadically when calling `TdApi.GetChatHistory()` for superchat with topics. (meaning it has negative chatId)
If I wait for 1-2 (sometimes 5-10) minutes and execute the same code again, it works, but not immediately. (For example, when I wrote this text and checked again - it worked, but did not work immediately after previous execution)
The problem is that I do not change ChatId, it remains the same. It is especially annoying when trying to debug code.

The error is as follows:
```
An unhandled exception of type 'TdLib.TdException' occurred in System.Private.CoreLib.dll
Chat not found
```
Environment: Win 10 / net6.0. 

I tried signing in again, it did not help

Any ideas? Or is there anything I missed?
Thanks in advance!

**Comment by ForNeVeR** [comment]
I think this should be a question for the upstream project. We only provide the API to call certain things from tdlib. If they decide that your chat doesn't exist, then it has to be something on server :(
