### ISSUE TITLE
[BUG] chat_id has a preceding -100

### ISSUE THREAD

**Issue by dojo90** [egramtel/tdsharp#20]
If you get a new `Message` the `chat_id` got a preceding `-100` on the id.
Is this a bug?

The right id is `1128794996`:

![grafik](https://user-images.githubusercontent.com/17551597/61625517-3fa14800-ac7b-11e9-99da-e029a981a1fe.png)

**Comment by x2bool** [comment]
I am pretty sure that channels and groups always have negative chat_id. The real question is probably: why UpdateChannelReadMessagesContents has positive id, and why it's called channel_id and not chat_id. I'll investigate.

**Comment by x2bool** [comment]
I don't know why Telegram devs decided to use channel_id, but it's their decision and there is no bug in TDSharp. Deserialization is working correctly. I am closing this for now, feel free to reopen if you have some other info.
