### ISSUE TITLE
How to handle responses?

### ISSUE THREAD

**Issue by Crispried** [egramtel/tdsharp#22]
Hello,

For example I want to handle GetChat response. The type of Update which is retrieved for it is UpdateFile (what sounds logically since the purpose is to store that data to local db). However I don't want to store any data at all and I want work with API only in online mode. Moreover there is no specification which file will be updated (I believe the same type will be retrieved for GetMessages for instance)

So, how I can access actual data which is retrieved for GetChat API? Why the logic was changed to handle Update object instead of BaseObject as it is in original tdlib? It's useful when you can simply cast response data to object type which is expected to be retrieved.

Maybe I didn't get smth so, please clarify that.

Thank you!

**Comment by x2bool** [comment]
Hello,

If I understood you correctly you are trying to get response for GetChat method via Updates. If I remember correctly this is how original tdlib does this. But TdSharp handles responses for you, no need for manual update handling. Just use async method ExecuteAsync:

```
var chat = await client.ExecuteAsync(new TdApi.GetChat{ ... });
```

Updates are used for event handling. For example when someone sends a message to you. This is why all updates have common base class: Update.

**Comment by Crispried** [comment]
@x2bool 
Ok, but how to get Chat object from the response? In original library GetChats retrieves Chat object (so I can compare retrieved data with Chat type). However currently the type which is retrieved for GetChat is updateFile. It has parent Update which has parent Object however the logic below doesn't

```
_client.UpdateReceived += async (sender, data) =>{
if ((TdApi.Object)data is Chat)
    {
        var chat = ((TdApi.Object)data as Chat);
    }
}
```
