### ISSUE TITLE
"tdjson.dll" could not be found

### ISSUE THREAD

**Issue by omidshafai** [egramtel/tdsharp#23]
Hello, this error occurs when I call "new Client()":

`Unable to load DLL 'tdjson.dll': The specified module could not be found.`

**Comment by x2bool** [comment]
Did you install https://github.com/ForNeVeR/tdlib.native ?

**Comment by aloji** [comment]
Hi,

I have the same error when deploying in azure web app. Any suggestions?

System.DllNotFoundException: Unable to load DLL 'tdjson.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at TdLib.Bindings.WindowsBindings.td_json_client_create()
   at TdLib.TdJsonClient..ctor()
   at TdLib.TdClient..ctor()

```
    <PackageReference Include="TDLib" Version="1.6.0" />
    <PackageReference Include="tdlib.native" Version="1.6.0" />
```

Regards,
