### ISSUE TITLE
Failed to ExecuteAsync in the latest version?

### ISSUE THREAD

**Issue by mostafa8026** [egramtel/tdsharp#24]
My os: linux.
I update the tdlib to the latest version and use yout latest version but it hangs on ExecuteAsync and dont return received result, take a look at log:

```
11/3/19 12:47:07 PM - enabling tor proxy
[ 3][t 4][1572772627.691557407][Td.cpp:3548][#1][!Td][&td_requests]	Receive request 3: addProxy {
  server = "127.0.0.1"
  port = 9050
  enable = true
  type = proxyTypeSocks5 {
    username = ""
    password = ""
  }
}
[ 3][t 4][1572772627.691611528][Td.cpp:4672][#1][!Td][&td_requests]	Sending result for request 3: proxy {
  id = 2
  server = "127.0.0.1"
  port = 9050
  last_used_date = 1572772581
  is_enabled = true
  type = proxyTypeSocks5 {
    username = ""
    password = ""
  }
}
```

The log shows that the result sent, but the tdjsonclient does not receive it and ExecuteAsync hang forever.

PS: Everything was fine with 1.3 version.

**Comment by x2bool** [comment]
What is your version? Do you use TdLib.Native? From Nuget or source?

**Comment by mostafa8026** [comment]
no I built it by my own using command-line from source code. it gives me libtdjson.so and I copy it to my program location.
I'm using latest version: 1.5.1

**Comment by x2bool** [comment]
This repo contains binding for 1.4 at the moment

**Comment by mostafa8026** [comment]
How can i add 1.5?
how to help you?

**Comment by mostafa8026** [comment]
Could you please give me a tip to handle this situation?
thank you.

**Comment by x2bool** [comment]
I will test class generator with 1.5, and we will see if it's resolves this issue.

**Comment by mostafa8026** [comment]
When do you have time to check it??

**Comment by mostafa8026** [comment]
Could you please share your generator with us.

**Comment by mostafa8026** [comment]
I've just added a temporary fix in the pr #27

**Comment by x2bool** [comment]
Thanks for patiently waiting for 1.5. I just updated this repo. If something does not work for you feel free to open another issue.

**Comment by lhaus** [comment]
this is still happening for me with 1.5 .dylib on macOS 10.15.1, just gets stuck after async execution. 
```
client.ExecuteAsync(new TdApi.GetUser
            {
                UserId = uid
            }).Result;
```
