### ISSUE TITLE
Xamarin support

### ISSUE THREAD

**Issue by hihain** [egramtel/tdsharp#25]
How about Xamarin support to build an Android app in Visual Studio using C#?

**Comment by x2bool** [comment]
I have no idea what needs to be done for Xamarin support. I will gladly accept contributions from someone who knows how to develop for Xamarin.

**Comment by StruninIhor** [comment]
> How about Xamarin support to build an Android app in Visual Studio using C#?
---
I think that is related to https://github.com/tdlib/td/issues/906
---
@hihain, you can use .NET Standard libraries in Xamarin since you will provide tdlib_json.dll built for Android. Did you try to do that?

**Comment by hihain** [comment]
@StruninIhor That is a great hint and I guess it works. For the forseeable future I won't have time to try this. But I assume this issue will help other seeking what I looked for. Thanks a lot!
