### ISSUE TITLE
When this library update to the 1.5?

### ISSUE THREAD

**Issue by mostafa8026** [egramtel/tdsharp#26]
Since the latest version of tdlib is 1.5 and there is a lot of changes, especially in the authentications. Do you have any plan to update your library to the latest version?

P.S: take a look at this issue: https://github.com/tdlib/td/issues/561

**Comment by x2bool** [comment]
Hi! I will try to generate 1.5 on the next weekend.

**Comment by mostafa8026** [comment]
I've just added a temporary fix in the pr #27

**Comment by mostafa8026** [comment]
I've just added a temporary fix in the pr #27

**Comment by x2bool** [comment]
Thanks for patiently waiting for 1.5. I just updated this repo. If something does not work for you feel free to open another issue.
