### ISSUE TITLE
Failed to rename binlog

### ISSUE THREAD

**Issue by daparici** [egramtel/tdsharp#29]
Hi,

I use tdsharp to download several files simultaneously from Telegram. Sporadically I receive and exception when tdlid tries to rename binlog and my app crashes. Do you know how can I avoid this?

[&status.is_error()]  Failed to rename binlog: [WindowsError : Access
denied. : 5 : Can't rename "C:\------\td.binlog.new" to "C:\------\td.binlog"]

I have no antivirus enabled.

**Comment by x2bool** [comment]
Hi,

This seems like a native error from tdlib. Consider opening an issue in https://github.com/tdlib/td

**Comment by daparici** [comment]
Ok. Thaks!
