### ISSUE TITLE
TdClientErrorTests never terminates

### ISSUE THREAD

**Issue by ForNeVeR** [egramtel/tdsharp#30]
Currently, the test `TDLib.Tests.TdClientErrorTests.Execute_WhenErrorExpected_ThrowsTdException` doesn't work, because it will never terminate.

Tested on Windows and macOS.

**Comment by x2bool** [comment]
@ForNeVeR At first glance it seems like it's not our fault. For some reason testReturnError fails with a fatal error in log. I've created an issue in main TDLib repo: https://github.com/tdlib/td/issues/863 . Let's see what they will tell us.
