### ISSUE TITLE
"tdjson.dll" could not be found, despite everything

### ISSUE THREAD

**Issue by Inetov** [egramtel/tdsharp#36]
Hello!

- I tried install tdlib.native,
- I tried download release from https://github.com/ForNeVeR/tdlib.native/releases and copy "tdjson.dll" to output directory.
- I tried even put full path to dll in TdLib.Bindings.WindowsBindings
`private const string Dll = "tdjson.dll";`

But still get the error:
`Unable to load DLL 'tdjson.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)`

Could the reason be that I use Core 2.1?
Windows 10, VS 2017

**Comment by x2bool** [comment]
Hi! Which version of tdsharp and tdlib.native you tried?

**Comment by x2bool** [comment]
.NET Core 2.1 should be fine

**Comment by Inetov** [comment]
> Hi! Which version of tdsharp and tdlib.native did you try?

latest, 1.6.0

**Comment by aloji** [comment]
Hi @Inetov , 

the version 1.6.0 is working fine for me using .Net Core 2.2

my problem is deploying in azure web apps - https://github.com/egramtel/tdsharp/issues/23#issuecomment-593346889

**Comment by x2bool** [comment]
@aloji I wonder if Azure Web Apps runs on x86

**Comment by x2bool** [comment]
@Inetov Is your Windows 64 or 32 bit version?

**Comment by Inetov** [comment]
But if I create local project (console app and took the following steps:

1. Added from NuGet TDLib
2. Added from NuGet TDLib.Api
3. Added from NuGet tdlib.native

and still get the error.
What am I missing?

**Comment by Inetov** [comment]
> 
> 
> @Inetov Is your Windows 64 or 32 bit version?

64

**Comment by aloji** [comment]
@x2bool In Azure, I can choose the option to 32 or 64 bit, In both version I received the same error.

@Inetov I installed this nugets:

```
 <PackageReference Include="TDLib" Version="1.6.0" />
 <PackageReference Include="tdlib.native" Version="1.6.0" />
```

**Comment by x2bool** [comment]
@ForNeVeR any ideas? TDLib.Native nuget package works for me.

**Comment by Inetov** [comment]
I updated to 2.2, nothing change
[screen here](https://github.com/egramtel/tdsharp/issues/36#issuecomment-593364925)

**Comment by ForNeVeR** [comment]
@Inetov, could you please show your `.csproj` file?

**Comment by Inetov** [comment]
> 
> 
> @Inetov, could you please show your `.csproj` file?


```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TDLib" Version="1.6.0" />
    <PackageReference Include="TDLib.Api" Version="1.6.0" />
    <PackageReference Include="tdlib.native" Version="1.6.0" />
  </ItemGroup>

</Project>
```

**Comment by Inetov** [comment]
Any ideas?

**Comment by x2bool** [comment]
Could you try copying tdjson.dll and its dependencies into your output folder manually, and see if it works?

**Comment by Inetov** [comment]
> 
> 
> Could you try copying tdjson.dll and its dependencies into your output folder manually, and see if it works?

I already did this, but now I repeat again:
![изображение](https://user-images.githubusercontent.com/45286374/75876778-646fb780-5e27-11ea-9bf0-d4b768ff112b.png)

As you can see: path is correct, dll is present, but nothing change.

**Comment by x2bool** [comment]
tdjson.dll has dependencies on Windows. You have to copy them too

**Comment by Inetov** [comment]
> 
> 
> tdjson.dll has dependencies on Windows. You have to copy them too

not understood

**Comment by x2bool** [comment]
@Inetov 

<img width="359" alt="image" src="https://user-images.githubusercontent.com/892945/75882232-ccc39680-5e31-11ea-8c31-374bb1396dd1.png">

**Comment by Inetov** [comment]
@x2bool done! nothing change.

**Comment by avdynut** [comment]
Hi, I ran into the same problem. I tried to run _TDLib.Samples.GetChats_ test project. The solution is to install **tdlib.native** and add **x64** platform in Configuration Manager.
Also, I cannot install tdlib.native to .NET Framework 4.8 project. So, as I can undestand, tdsharp works only with .NET Core and x64 platform.

**Comment by ForNeVeR** [comment]
@Inetov, could you please try to debug your case with [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon)?

Set it up to pick any operations from `dotnet.exe` process, reproduce the issue, and then check the file operation history (or post it here, I'll check it our myself). It definitely tries to load some file that's absent from your machine, and we should determine which one.

**Comment by ForNeVeR** [comment]
@avdynut, TDSharp should work on .NET Framework. The reason you have an error is that .NET Framework (and older versions of .NET Core, anything older than 2.1 I believe) don't support loading DLLs from .NET Core native NuGet package layout.

For .NET Framework, you'll have to manually copy dependencies from the package to your output, and then everything should work. You may want to check [my article on copying files from NuGet packages](https://fornever.me/en/posts/2018-05-24-adding-items-from-old-packages.html) on .NET SDK projects.

Also, AFAIK, TDSharp has nothing x64-specific, so it should be compatible with both x86 and x86_64 versions of tdlib.

TDLib.Native, on the other hand, has no 32-bit binaries published, since I had no use of them. If you think they should be published for some platforms (you're on Windows, I presume?), then please [report an issue](https://github.com/ForNeVeR/tdlib.native). I think I could publish 32-bit builds at least for the platforms for which it's easy to do.

**Comment by Inetov** [comment]
> 
> 
> @Inetov, could you please try to debug your case with [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon)?

I have setup a filter by name "tdjson.dll".
And we can see that the dll was found. [Logfile.zip](https://github.com/egramtel/tdsharp/files/4303713/Logfile.zip)

**Comment by ForNeVeR** [comment]
@Inetov 
> I have setup a filter by name "tdjson.dll".

You shouldn't have done that. Please post logs without filter (or add a filter for `*.dll` for instance).

We already know that the system is able to find our DLL. It is one of dependencies that wasn't found.

**Comment by Inetov** [comment]
ok, clear run without copy dll in output directory. filter ".dll"
[Logfile.zip](https://github.com/egramtel/tdsharp/files/4311128/Logfile.zip)

**Comment by avdynut** [comment]
@Inetov have you tried to set target platform from Any CPU to x64?

**Comment by Inetov** [comment]
> 
> 
> @Inetov have you tried to set target platform from Any CPU to x64?

yes, no changes

**Comment by ForNeVeR** [comment]
@Inetov, thanks for your logs. Looks like your case is exactly the same as investigated in #39. Try to install the latest MSVC runtime. Possible mitigations are discussed in https://github.com/ForNeVeR/tdlib.native/issues/29.

**Comment by Inetov** [comment]
> 
> 
> @Inetov, thanks for your logs. Looks like your case is exactly the same as investigated in #39. Try to install the latest MSVC runtime. Possible mitigations are discussed in [ForNeVeR/tdlib.native#29](https://github.com/ForNeVeR/tdlib.native/issues/29).

yes, it works after installation **vc_redist.x64.exe** from [MS site](https://support.microsoft.com/ru-ru/help/2977003/the-latest-supported-visual-c-downloads) thank you!
but these are additional actions, for this I am already using [TLSharp](https://github.com/sochix/TLSharp) library
