### ISSUE TITLE
download big file

### ISSUE THREAD

**Issue by 110vahid** [egramtel/tdsharp#41]
how download big file by tdsharp?
my code for download file is :
TdClient.DownloadFileAsync(fileId,priority:32,offset:0,limit:0,synchronous:false)

file size is 1.5 GB.
Is there a mistake in the code?

**Comment by x2bool** [comment]
Hi! TdSharp is just a wrapper around the native lib. These sorts of questions belong to the main repo: https://github.com/tdlib/td
