### ISSUE TITLE
Does offset in GetChatsAsync work?

### ISSUE THREAD

**Issue by njlr** [egramtel/tdsharp#42]
I would like to get all chats, but I might have more chats than the limit so I want to call `GetChatsAsync` multiple times. 

However, this code never terminates. 

```csharp
var offset = 0;
var limit = 3;

while (true)
{
  var chats = await client.GetChatsAsync(offset, limit);

  Console.Log(chats.ChatIds);

  if (chats.ChatIds.IsEmpty)
  {
    break;
  }

  offset += 1; // What should the next offset be?
}
```

**Comment by x2bool** [comment]
Hi! TdSharp is just a wrapper around the native lib. These sorts of questions belong to the main repo: https://github.com/tdlib/td

But before asking there I suggest looking at this article:
https://core.telegram.org/tdlib/getting-started#getting-the-list-of-chats

**Comment by njlr** [comment]
Since the example on the official `tdlib` is basically spaghetti, the important bit is to set the order _and_ offset. 

```csharp
var limit = 3;

var offset = 0;
var order = 0;

while (true)
{
  var chats = await client.GetChatsAsync(order, offset, limit);

  Console.Log(chats.ChatIds);

  if (chats.ChatIds.IsEmpty)
  {
    break;
  }

  var lastChatId = chats.ChatIds.Last;

  var chat = await client.GetChatAsync(lastChatId);

  order = chat.Order;
  offset = chat.Id;
}
```
