### ISSUE TITLE
Data is incorrect if telegram account is protected by cloud password

### ISSUE THREAD

**Issue by StruninIhor** [egramtel/tdsharp#43]
When I tried to use code from example, I found that if I have a cloud password, I receive Update with Type UpdateAuthorizationState -> AuthorizationStateWaitPassword. That is OK. But the issue is that I receive the same update with exactly the same data even if I will remove that cloud password or change it (changed hint). There are two ways how to reproduce that issue:
**Repro steps**
1. Add a cloud password to your account.
2. Try to login using existing code, but add update handler for\
 ```UpdateAuthorizationState->AuthorizationStateWaitPassword``` update type. 
3. Remove cloud password **OR** Change it and change hint
4. Try that again. And receive the same data.
5. Even if you will provide the correct password you will get ```HTTP 401``` from the server.
---
Maybe I did something wrong and that is the correct behavior?
I think the issue is related to the tdlib_json.dll library because data is provided by it. Maybe I have to move that issue to tdlib repo?
I can provide a sample code to reproduce if needed. 

---
I tested the same behaviour with TLSharp and it works fine.

**Comment by x2bool** [comment]
This is how native tdlib works. This type of questions should be addressed to Telegram devs.
