### ISSUE TITLE
NuGet: The package does not contain any assembly references or content files that are compatible with that framework.

### ISSUE THREAD

**Issue by luximil** [egramtel/tdsharp#44]
Hello everyone,

does someone what to do to install the TDLib package through NuGet if I get the following error message?

> Could not install package 'TDLib 1.6.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0,Profile=Client', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by ForNeVeR** [comment]
Are you really trying to install it into a project using _.NET 4 client profile_?

**Comment by luximil** [comment]
Yes, I am, because I'm also using another API which works in the .Net framework version 4.0.

**Comment by ForNeVeR** [comment]
This package only supports .NET Standard 2.0+. I'm not sure if it will work for .NET 4.0, but you may try rebuilding it for net40, if you want.
