### ISSUE TITLE
Can i authorize with TData folder  or with session key by this lib? 

### ISSUE THREAD

**Issue by victor-pashuk** [egramtel/tdsharp#45]
Can i authorize with TData folder  or with session key by this lib?

**Comment by x2bool** [comment]
I am not sure what is TData folder and session key. What do you mean?

**Comment by victor-pashuk** [comment]
Telegram Desktop  has a "tdata" folder where it stores some encrypted files. This folder is normally found at "~/.local/share/TelegramDesktop" on Linux and at "%USERPROFILE%\AppData\Roaming\Telegram Desktop" on Windows.
Files in this folder contains a crypted session key and we can authorize  accaunt just 
substitute this folder via telegram desctop. There are other tools for grabbing a session key from "tdata" and i need to know, can i authorize via session key by this library or not.

**Comment by victor-pashuk** [comment]
Also can you say where tdsharp keep a session afrer first authorization?

**Comment by x2bool** [comment]
I don't know whether Telegram Desktop uses the same format. Tdlib (and TDSharp) keeps session where you configure it via `TdlibParameters`

**Comment by bsglinux16** [comment]
> Can i authorize with TData folder or with session key by this lib?

Are you talking about a string session like in pyrogram?

if it is a must-have feature.
