### ISSUE TITLE
How to download photo from message content in Telegram Channel

### ISSUE THREAD

**Issue by Jycjmf** [egramtel/tdsharp#46]
Hey, guys.
I want to download photo from message content in Telegram Channel, but I cant find anything useful in "TdLib.Samples.GetChats" samples.
Could anyone give me some advice or samples? Thanks.

**Comment by x2bool** [comment]
Check out  https://github.com/egramtel/tdsharp/blob/master/TDLib.Api/Objects/MessagePhoto.cs

Basically you have to check if the message content is photo, then download it using https://github.com/egramtel/tdsharp/blob/master/TDLib.Api/Functions/DownloadFile.cs , and subscribe to https://github.com/egramtel/tdsharp/blob/master/TDLib.Api/Objects/UpdateFile.cs to track download progress.
