### ISSUE TITLE
Create tddroid Branch Please

### ISSUE THREAD

**Issue by bsglinux16** [egramtel/tdsharp#48]
I created a prebuilt project for Xamarin and other arm platforms.
To use libtdjsonandroid library in Xamarin
I had to edit the bindings of the tdsharp project
It would be nice if you add it as a branch
this is my project: https://github.com/bsglinux16/tddroid

I'm waiting for your answer

**Comment by x2bool** [comment]
That is really cool. What exactly did you change in the bindings? Could we integrate this into the main branch?

**Comment by bsglinux16** [comment]
https://github.com/tdlib/td/issues/77#issuecomment-640719893
In the comment here, android wrapper compilation files for tdlib are shared.
To use tdsharp in xamarp, libtdjsonandroid with arm compilation was required.
tdjson_client_create and a few functions added _ signs in the wrapper
tdsharp did not work because it was looking for these functions without the _ sign
I added _ sign to the beginning of functions like td_json_create in files in LinuxBindings.cs and Interop.cs
You can view the changes here https://github.com/bsglinux16/tddroid/tree/master/tdsharp/TDLib/Bindings
https://github.com/bsglinux16/tddroid/blob/master/tdbuild/td/tddroid/libtdjsonandroid/td_json.cpp
I changed the functions in these c ++ codes in tdsharpta so it worked in xamar
If you want you can add it as a branch

**Comment by bsglinux16** [comment]
![image](https://user-images.githubusercontent.com/35398147/90517307-e5b8cd80-e16d-11ea-96ed-ca4cc0358293.png)
![image](https://user-images.githubusercontent.com/35398147/90517357-f5381680-e16d-11ea-9d73-8583e9e5594a.png)
![image](https://user-images.githubusercontent.com/35398147/90517443-11d44e80-e16e-11ea-91a7-ebef18eb320d.png)

**Comment by x2bool** [comment]
The right way of doing this would be something like `XamarinAndroidBindings` in the same branch probably. We just need a way to detect when it's running on Android.

**Comment by bsglinux16** [comment]
IsOsPlatform (OSPlatform.Xamarin) or Android
Is Something Like?

**Comment by bsglinux16** [comment]
Xamarin Platform Detected as Linux
If It Is Detected On Android I Guess This Can Be Done.

**Comment by levlam** [comment]
@ForNeVeR The issue with different function names is supposed to be resolved before these scripts became an official build examples for Android, but it seems that there is no easy way to fix this. For now, they are just examples of how TDLib can be built for Android, but given that there are no other examples, it make sence to support these names for now. The best way would be to try both function names on Android.

**Comment by bsglinux16** [comment]
If you try to use the library without changing the tdsharp codes, you will get errors such as td_json_client_create not found.
Definitions for this should change.

**Comment by x2bool** [comment]
> 
> 
> We could just allow the user to manually select the platform-specific implementation, so on Android they'd just pass `new TdClient(TdJsonPlatform.Xamarin)`, or something like that.

Looks good to me. I wonder whether Xamarin going to stay as official name for the Android implementation, or .NET 5 will somehow change this.

Also as I understand iOS version of tdlib does not require underscores. It means we'll have to differentiate between iOS and Android bindings.

**Comment by bsglinux16** [comment]
> > We could just allow the user to manually select the platform-specific implementation, so on Android they'd just pass `new TdClient(TdJsonPlatform.Xamarin)`, or something like that.
> 
> Looks good to me. I wonder whether Xamarin going to stay as official name for the Android implementation, or .NET 5 will somehow change this.
> 
> Also as I understand iOS version of tdlib does not require underscores. It means we'll have to differentiate between iOS and Android bindings.

I guess system.maui was coming instead of xamarin

And only android require underscores

**Comment by bsglinux16** [comment]
When will the change be made?

**Comment by x2bool** [comment]
@bsglinux16 feel free to open a pull request

**Comment by bsglinux16** [comment]
> @bsglinux16 feel free to open a pull request

How do I open a pull request from a non-fork project?

**Comment by ForNeVeR** [comment]
There's no possibility. Could you create a fork?

**Comment by bsglinux16** [comment]
Issue Moved to Pull Request #50 
@ForNeVeR @x2bool @levlam
