### ISSUE TITLE
Message Forwarding not always working - Gives Error : Chat to forward messages to not found

### ISSUE THREAD

**Issue by habeebmatrix** [egramtel/tdsharp#49]
The Message forwarding option is working at times and fails at times with error: Chat to forward messages to not found
All parameters are valid and having proper value. 
Any idea what could be the reason?
I tried 2 methods TdClient.ForwardMessagesAsync and TdClient.Send
```
_client = new TdClient();
_client.UpdateReceived += async (sender, update) =>
//////
case TdApi.Update.UpdateNewMessage u when u.Message.Content.GetType() == typeof(TdApi.MessageContent.MessageText):
await _client.ForwardMessagesAsync(destinationChatId, u.Message.ChatId, new long[1] { u.Message.Id },
                                    new TdApi.SendMessageOptions { DisableNotification = false, FromBackground = true }, true, true, false);
```

Alternately, below method was used and this method doesn't give error, but forwarding doesn't happen. If i run both together, its clear that, if it works both works. If fails, both fails.
```
_client.Send(new TdApi.ForwardMessages
{
	ChatId = destinationChatId,
	FromChatId = u.Message.ChatId,
	Options = new TdApi.SendMessageOptions { DisableNotification = false, FromBackground = true },
	AsAlbum = true,
	SendCopy = true,
	RemoveCaption = false,
	MessageIds = new long[1] { u.Message.Id }
});

```

**Comment by habeebmatrix** [comment]
Thanks @x2bool for the response. 
destinationChatId is valid.
May be then, I should raise the question at "https://github.com/tdlib/td/", but just worried if they would say this library is not supported and ask to use there CSharp example.

**Comment by x2bool** [comment]
you can enable logging and post request and response.

**Comment by habeebmatrix** [comment]
Hi @x2bool . I had found this mention of enable logging in other issue threads. Could you please help me understand how to enable logging in this case? I have :
`TdLog.SetVerbosityLevel(0);`
This doesn't write any extra logs.

**Comment by x2bool** [comment]
https://github.com/tdlib/td/blob/81cb9da8873042544cc50919dc4e0350aae1f7ea/td/telegram/td_log.h#L50

```
*                                 Value 0 corresponds to fatal errors,
 *                                 value 1 corresponds to errors,
 *                                 value 2 corresponds to warnings and debug warnings,
 *                                 value 3 corresponds to informational,
 *                                 value 4 corresponds to debug,
 *                                 value 5 corresponds to verbose debug,
 *                                 value greater than 5 and up to 1024 can be used to enable even more logging.
```

I would try verbosity level >= 5

**Comment by habeebmatrix** [comment]
This is great help. I will try this.

**Comment by habeebmatrix** [comment]
Thanks Solved issue by calling GetChats once before sending first message
