### ISSUE TITLE
Please Update the Library Tdlib Latest Version

### ISSUE THREAD

**Issue by bsggr78** [egramtel/tdsharp#53]
Hello there

Added Many New Features to Telegram and Tdlib.

Many of these Innovations don't include tdsharp.

Can library developers update the library?

**Comment by bsggr78** [comment]
@x2bool @ForNeVeR @Behnam-Emamian 
still the library has not been updated.
an update is now needed urgently.

**Comment by x2bool** [comment]
ok. I will try to generate 1.7.0 bindings

**Comment by bsggr78** [comment]
> ok. I will try to generate 1.7.0 bindings

okay thanks.
most commands were starting to cause problems now.
I hope this will be resolved by updating.

**Comment by JosXa** [comment]
I'm also trying to get it to work for the first time and there seem to be some options coming in that just don't work with the layer..? In any case, the example ain't working for me. So would also appreciate very much to at least be able to make a connection :)

If you need any help generating the new bindings let us know 👍

**Comment by x2bool** [comment]
Hey everyone! 1.7 is here. Also there is brand new code generator in this repo: https://github.com/egramtel/tdsharp/tree/master/TDLib.CodeGen (written in F#)

I did not push NuGet packages yet, but the project compiles and the tests seem to pass. Additional testing is needed however. So whoever wanted to help, you can help by compiling the code and running it in your application.

**Comment by moroz69off** [comment]
> Hey everyone! 1.7 is here.
> 
>  So whoever wanted to help, you can help by compiling the code and running it in your application.

I will now start a new project using your tdsharp.
-[ ] I will report on the results tomorrow.

**Comment by bsggr78** [comment]
> Selam millet! 1.7 burada. Ayrıca bu depoda yepyeni bir kod oluşturucu var: https://github.com/egramtel/tdsharp/tree/master/TDLib.CodeGen (F # ile yazılmıştır)
> 
> Henüz NuGet paketlerini göndermedim, ancak proje derleniyor ve testler başarılı görünüyor. Ancak ek testlere ihtiyaç vardır. Böylece kim yardım etmek isterse, kodu derleyerek ve uygulamanızda çalıştırarak yardımcı olabilirsiniz.

great!
we look forward to the new version.

**Comment by bsggr78** [comment]
> Hey everyone! 1.7 is here. Also there is brand new code generator in this repo: https://github.com/egramtel/tdsharp/tree/master/TDLib.CodeGen (written in F#)
> 
> I did not push NuGet packages yet, but the project compiles and the tests seem to pass. Additional testing is needed however. So whoever wanted to help, you can help by compiling the code and running it in your application.

great!
we look forward to the new version.


Can you tell me a little bit about what codegen does?

**Comment by moroz69off** [comment]
So. Everything went smoothly when I deployed the CodeGen project in my solution, except for xunit.runner.visualstudio 2.4.3.
Maybe I'll have to delete the CodeGen project to continue working, but still wondering: how to fix this?
~~~
The package "xunit.runner.visualstudio 2.4.3" has been restored with ".NETFramework, Version = v4.6.1, .NETFramework, Version = v4.6.2, .NETFramework, Version = v4.7, .NETFramework, Version = v4. 7.1, .NETFramework, Version = v4.7.2, .NETFramework, Version = v4.8 ", not the target project framework" .NETStandard, Version = v2.0 ". This package may not be fully compatible with your project.
~~~
You cannot change the target platform. The project is sealed somewhere and the platform change is not active.

If you look at what is wrong, then it is here:
[https://github.com/moroz69off/MRZtdlflh_solution](https://github.com/moroz69off/MRZtdlflh_solution)

**Comment by ForNeVeR** [comment]
I'll try to work on releasing the correponding version of tdlib.native this week.

**Comment by bsggr78** [comment]
> I'll try to work on releasing the correponding version of tdlib.native this week.

I guess I can help with native compilation.

**Comment by x2bool** [comment]
A bit of clarification: CodeGen project is only needed to generate APIs from Telegram's Type Language. To make your app work you only need to include TdLib and TdLib.Api packages as before (and TdLib.Native if you need prebuilt lib). I'll look into xunit target framework warnings, but you won't need it to use TDLib in your app.

**Comment by moroz69off** [comment]
OK, thanks. I compiled the rest myself, added it to the project and it works. Just like tdlib / td itself too

**Comment by forconz** [comment]
@moroz69off could you give a sample project?

**Comment by moroz69off** [comment]
> @moroz69off could you give a sample project?

My example project - https://github.com/moroz69off/MRZtdlflh_solution

**Comment by x2bool** [comment]
1.7.0 packages have been published to nuget.org

**Comment by bsggr78** [comment]
Thank you all for your work.

**Comment by JosXa** [comment]
The other day I saw that tdlib.native was still on 1.6 on my platform. What's the relationship with that library/nuget package exactly?
