### ISSUE TITLE
some methods not found

### ISSUE THREAD

**Issue by graymind123** [egramtel/tdsharp#55]
it seems, a lot of methods from  [mehtods](https://core.telegram.org/methods) is omitted. Is there any way to call these methods like TLsharp general solution :

//Create request 
  var req = new TLRequestSetTyping()
  {
    Action = new TLSendMessageTypingAction(),
    Peer = new TLInputPeerUser() { UserId = user.Id }
  };

  //run request, and deserialize response to Boolean
  return await client.SendRequestAsync<Boolean>(req);

**Comment by x2bool** [comment]
Hi! TDLib is not 1:1 mapping of Telegram API. In your case however https://github.com/egramtel/tdsharp/blob/6ff96f3943be88bb79f9e3b68d83a7cb77b361cf/TDLib.Api/Objects/ChatActionTyping.cs should do the job.
