### ISSUE TITLE
What's content of the compiled library?

### ISSUE THREAD

**Issue by forconz** [egramtel/tdsharp#56]
You're recommended to use precompiled version of TDLib native artifacts from NuGet: TDLib.Native

NuGet

Note that tdlib.native is not a dependency of TDLib, so you may choose to build the binaries yourself and provide them at the runtime.

To do that, build TDLib and put **the compiled library** into your project's output directory

![20210113064446](https://user-images.githubusercontent.com/9990289/104383472-d8600d80-556a-11eb-89ba-205794fa25eb.png)

![20210113064319](https://user-images.githubusercontent.com/9990289/104383412-c4b4a700-556a-11eb-874a-fa46117a0c5a.png)

How to put **the compiled library** into my project's output directory?
![20210113064640](https://user-images.githubusercontent.com/9990289/104383652-2248f380-556b-11eb-99ea-ff92ae1ec769.png)

**How to copy?**

tdjson.dll (Windows) (optionally accompanied by other DLL files from the build directory if you want to bundle OpenSSL and ZLib dependencies as well)
libtdjson.dylib (MacOS)

libtdjson.so (Linux)

**Comment by moroz69off** [comment]
I have compiled files here:
![Снимок](https://user-images.githubusercontent.com/6573955/104663282-b3d87280-56dd-11eb-8796-e64cc2f74751.PNG)

**Comment by JosXa** [comment]
I think you wanna add them next to the csproj in something like a `lib` folder and then use `CopyToOutputDirectory` so they'll end up in your build output: https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2019#compile
