### ISSUE TITLE
 _client.UpdateReceived how do i access the values received

### ISSUE THREAD

**Issue by rsibweza** [egramtel/tdsharp#58]
I have tried so hard the past 2 days to access the values received upon update received.

I am getting the data on the console but the issue is to how to access them dynamically

please guide me.

**Comment by x2bool** [comment]
I need code sample to help you. What do you mean by dynamically?

**Comment by dancojocaru2000** [comment]
@rsibweza In case you still have an issue, you receive an Update class but that is a specialized object. In order to access the specialized object, you need to either check it in an `if` or a `switch` statement, like so:

```csharp
client.UpdateReceived += (client, update) => 
{
    if (update is UpdateAuthorizationState uas) 
    {
        // do something with the uas variable
    }
};
```

```csharp
client.UpdateReceived += (client, update) => 
{
    switch (update) 
    {
        case UpdateAuthorizationState uas:
            // do something with the uas variable
            break;
    }
};
```

It took me a little bit to figure this out too.
