### ISSUE TITLE
ExecuteAsync thread seems to be blocked after the first call

### ISSUE THREAD

**Issue by shpendpalushi** [egramtel/tdsharp#60]
From the samples in the repo in the GetChannels method, the TdApi.GetChats works well and the list of Chats is getting returned. Inside foreach the TdApi.GetChat returns a value the first time but after that when it gets called for the second time seems like thread to be blocked and no more data is getting received.

**Comment by x2bool** [comment]
Would you mind providing the code?

**Comment by shpendpalushi** [comment]
`public class ChatHub : Hub
    {
        public readonly static List<UserViewModel> _Connections = new List<UserViewModel>();
        public readonly static List<RoomViewModel> _Rooms = new List<RoomViewModel>();
        private readonly static Dictionary<string, string> _ConnectionsMap = new Dictionary<string, string>();
        private const string baseAPIUrl = "http://192.168.15.40:99/";

        private static readonly int ApiId = 3379882;
        private static readonly string ApiHash = "";
        private static readonly string PhoneNumber = ""; // must contain prefix
        private static readonly string _Code = "";

        private static readonly ManualResetEventSlim ResetEvent = new ManualResetEventSlim();
        private static bool _authNeeded;
        private static TdClient _client;


        private readonly ApplicationDbContext _context;
        private readonly IMapper _mapper;

        public ChatHub(ApplicationDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }
        public async Task GetTelegramData()
        {
            _client = new TdClient();
            _client.Bindings.SetLogVerbosityLevel(0);

            _client.UpdateReceived += async (sender, update) =>
            {
                switch (update)
                {
                    case TdApi.Update.UpdateOption option:
                        //await _client.ExecuteAsync(new TdApi.SetOption
                        //{
                        //    DataType = option.DataType,
                        //    Extra = option.Extra,
                        //    Name = option.Name,
                        //    Value = option.Value
                        //});
                        break;
                    case TdApi.Update.UpdateAuthorizationState updateAuthorizationState when updateAuthorizationState.AuthorizationState.GetType() == typeof(TdApi.AuthorizationState.AuthorizationStateWaitTdlibParameters):
                        await _client.ExecuteAsync(new TdApi.SetTdlibParameters
                        {
                            Parameters = new TdApi.TdlibParameters
                            {
                                ApiId = ApiId,
                                ApiHash = ApiHash,
                                ApplicationVersion = "1.3.0",
                                DeviceModel = "PC",
                                SystemLanguageCode = "en",
                                SystemVersion = "Win 10.0"
                            }
                        });
                        break;
                    case TdApi.Update.UpdateAuthorizationState updateAuthorizationState when updateAuthorizationState.AuthorizationState.GetType() == typeof(TdApi.AuthorizationState.AuthorizationStateWaitEncryptionKey):
                        await _client.ExecuteAsync(new TdApi.CheckDatabaseEncryptionKey());
                        break;
                    case TdApi.Update.UpdateAuthorizationState updateAuthorizationState when updateAuthorizationState.AuthorizationState.GetType() == typeof(TdApi.AuthorizationState.AuthorizationStateWaitPhoneNumber):
                        _authNeeded = true;
                        ResetEvent.Set();
                        break;
                    case TdApi.Update.UpdateAuthorizationState updateAuthorizationState when updateAuthorizationState.AuthorizationState.GetType() == typeof(TdApi.AuthorizationState.AuthorizationStateWaitCode):
                        _authNeeded = true;
                        ResetEvent.Set();
                        break;
                    case TdApi.Update.UpdateUser updateUser:
                        ResetEvent.Set();
                        break;
                    case TdApi.Update.UpdateConnectionState updateConnectionState when updateConnectionState.State.GetType() == typeof(TdApi.ConnectionState.ConnectionStateReady):
                        break;

                    default:
                        ; // add a breakpoint here to see other events
                        break;
                }
            };

            ResetEvent.Wait();
            if (_authNeeded)
            {
                await _client.ExecuteAsync(new TdApi.SetAuthenticationPhoneNumber
                {
                    PhoneNumber = PhoneNumber
                });
                var code = _Code;
                await _client.ExecuteAsync(new TdApi.CheckAuthenticationCode
                {
                    Code = code
                });
            }
            //Todo - Add the method you need
            await foreach (var chat in GetChannels())
            {
                Debug.WriteLine(chat.Title);
                await foreach (var message in GeneralData.GetMessages(chat.Id))
                {
                    Debug.WriteLine(message.Content);
                }
            }

            

        }

        public static async IAsyncEnumerable<TdApi.Chat> GetChannels(long offsetOrder = long.MaxValue, long offsetId = 0, int limit = 1000)
        {
            var chats = await _client.ExecuteAsync(new TdApi.GetChats { OffsetOrder = offsetOrder, Limit = limit, OffsetChatId = offsetId });
            foreach(var chat in chats.ChatIds)
            {
                Debug.WriteLine(chat);
            }
            foreach (var chatId in chats.ChatIds)
            {
                var chat = await _client.ExecuteAsync(new TdApi.GetChat { ChatId = chatId });
                if (chat.Type is TdApi.ChatType.ChatTypeSupergroup || chat.Type is TdApi.ChatType.ChatTypeBasicGroup || chat.Type is TdApi.ChatType.ChatTypePrivate)
                {
                    yield return chat;
                }
            }
        }

 public override async Task OnConnectedAsync()
        {
            try
            {
                await GetTelegramData();

                var user = _context.Users.Where(u => u.UserName == IdentityName).FirstOrDefault();
                var userViewModel = _mapper.Map<ApplicationUser, UserViewModel>(user);
                if (userViewModel != null)
                {
                    userViewModel.Device = GetDevice();
                    userViewModel.CurrentRoom = "";

                    if (!_Connections.Any(u => u.Username == IdentityName))
                    {
                        _Connections.Add(userViewModel);
                        _ConnectionsMap.Add(IdentityName, Context.ConnectionId);
                    }

                }
                await Clients.Caller.SendAsync("getProfileInfo", user?.FullName, user?.Avatar);

            }
            catch (Exception ex)
            {
                await Clients.Caller.SendAsync("onError", "OnConnected:" + ex.Message);
            }
           // var dataResult = await GetTelegramData();
            await base.OnConnectedAsync();
            //var connResult = await Task.CompletedTask;
            return;
        }`

**Comment by x2bool** [comment]
Yeah! There is long running task in the background, and it's job is to receive data from the native lib. Which means all Tasks are resolved on one thread, and in your case the callback seems to be executing on that thread, and it causes the problem.

That is a design flaw in tdsharp, and it should be fixed. But in your case wrapping method calls in `await Task.Run(() => /* method call */)` could be a workaround.

**Comment by shpendpalushi** [comment]
I am closing it for now seems a reasonable solution

**Comment by xpfr** [comment]
The proposed workaround ("wrapping method calls in await Task.Run(() => /* method call */") does not seem to work in every case. I'm facing the same issue using the latest release 1.8.21.
As long as the API call is long running (GetChatHistory in my case), there is a deadlock happening.
Any hope we can reopen this issue?
