### ISSUE TITLE
[Suggestion] tdsharp automatically gets updated if tdlib is updated.

### ISSUE THREAD

**Issue by bsggr78** [egramtel/tdsharp#62]
Hello tdlib is a library that gets updates almost daily. tdsharp lags behind the intermediate versions after a while.

My suggestion is a program idea that when tdlib is updated, downloads the last tdlib code and recreates the functions of tdsharp.

so as tdlib is updated, tdsharp will be automatically updated.

**Comment by badicuady** [comment]
Hello! 

I agree that we need a way to update faster. I think the only thing missing is a way to update Methods.tl and Types.tl from TDLib.CodeGen project. How do you generate these files? Are they based on: [https://core.telegram.org/schema](https://core.telegram.org/schema)?

Thanks!

**Comment by bsggr78** [comment]
> Hello!
> 
> I agree that we need a way to update faster. I think the only thing missing is a way to update Methods.tl and Types.tl from TDLib.CodeGen project. How do you generate these files? Are they based on: https://core.telegram.org/schema?
> 
> Thanks!

Obviously I have no idea how it works.
However, if it is made directly from tdlib's site, the project can be updated by updating only those files.

**Comment by badicuady** [comment]
I think I found the source: [https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl](https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl).

This file is split into 2: first part is the Types.tl and if you search for "---functions---", then is the Methods.tl file.

Happy code generating!

**Comment by bsggr78** [comment]
> Sanırım kaynağı buldum: https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl .
> 
> Bu dosya 2'ye bölünmüştür: ilk bölüm Types.tl'dir ve "--- functions ---" ararsanız, Methods.tl dosyasıdır.
> 
> Mutlu kod üretme!

Can we update the project with only these?

**Comment by badicuady** [comment]
Yes, I have used td_api.tl and updated the files Types.tl and Methods.tl, regenerated the classes and recompiled the project. All working just fine.

**Comment by bsggr78** [comment]
thank you so much.
I completed the update
