### ISSUE TITLE
Listening for incomming messages using signalr

### ISSUE THREAD

**Issue by shpendpalushi** [egramtel/tdsharp#63]
I have been using tdsharp lately and want to integrate it with a signalr, .net core application and I can get users and chats but I want an event to be triggered when a new message comes. I have been calling 
`_client.UpdateReceived += async (sender, update) =>{...}
`
in the main method 
in the extending class of the SignalR.Hub abstract class. But it seems the UpdateRecieved method isn't being called, when a new message comes in.
Is there any way around it?
The structure of the project is:
- Program.cs (Where the Main method gets called)
- Startup.cs(Where SignalR gets configured)
- ChatHub (Where SignalR is implemented)

**Comment by x2bool** [comment]
Sorry, SignalR is out of scope for this project
