### ISSUE TITLE
Unknown class "inputChatPhotoStatic"

### ISSUE THREAD

**Issue by Archangel603** [egramtel/tdsharp#65]
I'm trying to create a new group and set its photo this way:
```
private readonly TdClient _client;
private readonly IConfiguration _configuration;

...

var newChat = await this._client.CreateNewSupergroupChatAsync(title, false);

await this._client.SetChatPhotoAsync(newChat.Id, new TdApi.InputChatPhoto.InputChatPhotoStatic
                {
                    Photo = new TdApi.InputFile.InputFileLocal
                    {
                        Path = this._configuration["TdLib:GroupPhoto"]
                    }
                });
```

where TdLibGroupPhoto is path to the image
But it causes "TdLib.TdException: Failed to parse JSON object as TDLib request: Unknown class "inputChatPhotoStatic""

.NET 5, TDLib 1.7.0, TDLib.Api 1.7.0, tdlib.native 1.6.0

**Comment by x2bool** [comment]
Hi! 1.7.0 does not work properly with native 1.6 lib.

**Comment by Archangel603** [comment]
Yep. Downgrading to 1.6.0 solved the problem. Thanks
