### ISSUE TITLE
Please add version tags to the repository

### ISSUE THREAD

**Issue by ForNeVeR** [egramtel/tdsharp#78]
Hello! Without tags, it's a bit hard to maintain tdlib.native (and it's hard to figure out what commit went to what version), since I use tests of this repo as smoke tests in tdlib.native.

Could you please mark future (or maybe even current and past?) versions with tags in the repository?

**Comment by x2bool** [comment]
Sure. I'll do that on the next weekend.

**Comment by x2bool** [comment]
Hi. Sorry it took so long. I tagged current state of master as v1.7.0

**Comment by ForNeVeR** [comment]
Thanks!
