### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by ForNeVeR** [egramtel/tdsharp#8]
For now, my main concern is that we could easily publish non-working library build (e.g. depending on non-working native assemblies) into NuGet. I think that we should add some rudimentary tests to check if the library works at least a little bit.

And the tests should execute on all supported platforms, for sure.

**Comment by x2bool** [comment]
@ForNeVeR here are some tests: https://github.com/egramtel/tdsharp/tree/master/TDLib.Tests

The test project currently references TDLib.Native-1.4.0-preview1 (Please tell me if we want to do this in some other way without referencing TDLib.Native directly)

The tests just passed on my Windows machine.

**Comment by x2bool** [comment]
Tests pass on Mac too.

**Comment by ForNeVeR** [comment]
Very well, thank you!
