### ISSUE TITLE
Error in log, but nothing in code 

### ISSUE THREAD

**Issue by juvenull** [egramtel/tdsharp#80]
Hi!

When i sent my phone number for authorization, the app is freeze.

```
else if (authorizationState is TdApi.AuthorizationState.AuthorizationStateWaitPhoneNumber)
{
    var task = client.ExecuteAsync(new TdApi.SetAuthenticationPhoneNumber { PhoneNumber = phoneNumber })
        .GetAwaiter().GetResult();
}
```

But i see in logs this picture (too Many Requests):

> [ 4][t 1][1628270246.887494802][Session.cpp:794][#1][!Session:2:main]	Session::on_message_result_error [id:6993367467929770288][error_code:420][msg:FLOOD_WAIT_60773]
> [ 3][t 1][1628270246.887503623][Session.cpp:803][#1][!Session:2:main][&net_query]	Return query error [Query:[id:262144][tl:0xa677244f][state:Query]]
> [ 3][t 1][1628270246.887513160][NetQuery.h:322][#1][!Session:2:main][&net_query]	Got error [Query:[id:262144][tl:0xa677244f][state:Query]] [Error : 420 : FLOOD_WAIT_60773]
> [ 3][t 1][1628270246.887523889][NetQuery.h:244][#1][!Session:2:main][&net_query]	[Query:[id:262144][tl:0xa677244f][state:Error][Error : 420 : FLOOD_WAIT_60773]] [state:sent to NetQueryDelayer]
> [ 3][t 1][1628270246.887541055][NetQuery.h:244][#1][!NetQueryDelayer][&net_query]	[Query:[id:262144][tl:0xa677244f][state:Error][Error : 420 : FLOOD_WAIT_60773]] [state:trying to delay]
> [ 3][t 1][1628270246.887547731][NetQuery.h:81][#1][!NetQueryDelayer][&net_query]	Resend[Query:[id:262144][tl:0xa677244f][state:Error]OK]
> [ 2][t 1][1628270246.887553215][NetQueryDelayer.cpp:72][#1][!NetQueryDelayer]	Failed: [Query:[id:262144][tl:0xa677244f][state:Query]] [timeout:60773.000000][total_timeout:60773.000000] because of [Error : 420 : FLOOD_WAIT_60773] from Session:2:main::Connect::Tcp::[149.154.167.50:443] to DcId{2} from [0.0.0.0:50513]
> [ 3][t 1][1628270246.887581348][NetQuery.h:322][#1][!NetQueryDelayer][&net_query]	Got error [Query:[id:262144][tl:0xa677244f][state:Query]] [Error : 429 : Too Many Requests: retry after 60773]
> [ 3][t 1][1628270246.887592315][NetQuery.h:244][#1][!NetQueryDelayer][&net_query]	[Query:[id:262144][tl:0xa677244f][state:Error][Error : 429 : Too Many Requests: retry after 60773]] [state:DcManager: send to DcManager]
> [ 3][t 1][1628270246.887601137][NetQuery.h:244][#1][!NetQueryDelayer][&net_query]	[Query:[id:262144][tl:0xa677244f][state:Error][Error : 429 : Too Many Requests: retry after 60773]] [state:sent to callback]
> [ 3][t 1][1628270246.887607812][AuthManager.cpp:743][#1][!AuthManager]	Receive result of query 262144, expecting 262144 with type 3
> [ 3][t 1][1628270246.887630462][Td.cpp:4617][#1][!Td][&td_requests]	Sending error for request 5: error { code = 429 message = "Too Many Requests: retry after 60773" }
> [ 4][t 1][1628270246.887649297][Session.cpp:1377][#1][!Session:2:main]	Wakeup after 29.999842

Why i dont get any exception?

**Comment by ForNeVeR** [comment]
Could you please check whether you have a copy of the code before or after https://github.com/egramtel/tdsharp/pull/92 was merged? It's possible you're just hitting the same deadlock, in case you're using the code in a UI application.

**Comment by ForNeVeR** [comment]
No answer from the reporter ⇒ closing for now. Feel free to comment if you still have any issues.
