### ISSUE TITLE
Memory leak on Ubuntu server

### ISSUE THREAD

**Issue by PringlesKing** [egramtel/tdsharp#82]
After a day, the consumption of RAM increases to **1400** MB instead of the usual 200 MB
My code: 
```
tg = tdClient;
tg.SetLogVerbosityLevelAsync(0);
// Already authenticated
tg.UpdateReceived += OnUpdate;

 private static async void OnUpdate(object sender, TdApi.Update update) {
 // Nothing here
}

```
Memory is occupied with every request, if you do something like this:
```
while (true) {
    var chatm = await _client.ExecuteAsync(new TdApi.GetSupergroupMembers { SupergroupId = 123, Limit = 100, Offset = offset });
    chatm = null;
    await Task.Delay(1000);
}
```
Memory will fill up very quickly, like a forkbomb

Im using tdlib.native 1.7.0

**Comment by x2bool** [comment]
Hi! Did you try to profile that leaking memory? Was is on the side of tdsharp or tdlib itself? Does your program ever crash with OutOfMemoryException?

My guess is that native tdlib just caches everything in RAM.
