### ISSUE TITLE
TDSharp on ARM

### ISSUE THREAD

**Issue by cplankl** [egramtel/tdsharp#96]
Hi there,

I want to use this library together with my Raspberry Pi 2 (Raspberry Pi OS). Is there any way how to accomplish this? I tried to use it but I think together with tdlib.native (only supports x64 as far as I have seen) it didn't start properly

**Comment by mediaexplorer74** [comment]
> Hi there,
> 
> I want to use this library together with my Raspberry Pi 2 (Raspberry Pi OS). Is there any way how to accomplish this? I tried to use it but I think together with tdlib.native (only supports x64 as far as I have seen) it didn't start properly

Hi there. Cool theme =) I want to use this library too for Multi-platform Telegram creating (Multigram, Uno Platform edition). Is there any way how to accomplish this? I tried to use tdsharp with demo sample, but I catched strange error "dll not found"

**Comment by ForNeVeR** [comment]
tdsharp is written in C# and is compatible with any platforms.

tdlib.native is not, since I don't know how to build for ARM on any CI. If you know this, contributions are welcome.

**Comment by cplankl** [comment]
I have found a tutorial here https://github.com/br0tda/tdlib_raspberry
Unfortunately it doesn't work anymore with the new telegram version. 

Now I try to build it on RPI 2.

**Comment by cplankl** [comment]
@mediaexplorer74
I have accomplished a running example on ARM (Raspberry Pi 2 with latest Raspbian OS)

I can give you a short example what I've done in the evening if you are interested

**Comment by x2bool** [comment]
As @ForNeVeR says, you are welcome to make contributions to TDLib.Native. TdSharp itself is compatible with any platforms supported by .NET
