### ISSUE TITLE
can not get list of messages related to a channel

### ISSUE THREAD

**Issue by vashdigital** [egramtel/tdsharp#97]
Hi,
I want to get the list of messages that are related to a specific channel, but when I Call the GetMessages with ChatId, the messages body is empty
By using the following code, I try to get the ChatId

`
var chats = await client.ExecuteAsync(new TdApi.GetChats { Limit = limit });
            foreach (var chatId in chats.ChatIds)
            {
                var chat = await client.ExecuteAsync(new TdApi.GetChat { ChatId = chatId });
                 if (chat.Title.StartsWith("ChannelName"))
                {
                    Console.WriteLine(chat.Id);
                    var executeAsync = await client.ExecuteAsync(new TdApi.GetMessages() {ChatId = chatId}); //the executeAsync.Messages is empty
                }

`

**Comment by fernandonajera** [comment]
Have you tried with `GetChatHistory`? I'm not sure `GetMessages` is designed to list all the messages of a chat.
See https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_chat_history.html

**Comment by vashdigital** [comment]
yes, that works, thnx
