### ISSUE TITLE
Latest version of tdlib.native has issues with GCC version

### ISSUE THREAD

**Issue by njlr** [egramtel/tdsharp#98]
I am having issues with the shard library `libtdjson.so` on Linux. 

According to `LD_DEBUG` it's an issue with GCC: 

> /usr/lib/x86_64-linux-gnu/libstdc++.so.6: error: version lookup error: version `GLIBCXX_3.4.26' not found (required by /home/libtdjson.so) (fatal)

What settings was the library compiled with?

What GCC version is required?

**Comment by AppcenterAucxis** [comment]
I have the same issue. I'm hosting on azure.

**Comment by ForNeVeR** [comment]
This is being investigated at https://github.com/ForNeVeR/tdlib.native/issues/51, I'm working on a fix.

(CI is very slow, and so my work is, too)

**Comment by AleksanderZverev** [comment]
> This is being investigated at [ForNeVeR/tdlib.native#51](https://github.com/ForNeVeR/tdlib.native/issues/51), I'm working on a fix.
> 
> (CI is very slow, and so my work is, too)

1.7.9.1 solved our problem with build, thank you ForNeVeR!

**Comment by AppcenterAucxis** [comment]
Fixed for me also. Thanks!!
